---
abstract: 'Template Toolkit plugin for HTML::Tooltip::JavaScript'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  File::Spec: 0.80
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Template::Plugin::Tooltip
name: Template-Plugin-Tooltip
no_index:
  directory:
    - inc
    - t
requires:
  HTML::Tooltip::Javascript: 0.03
  Scalar::Util: 1.15
  Template: 2.10
  perl: 5.005
resources:
  license: http://dev.perl.org/licenses/
version: 1.08
