
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.57
distribution_type: module
version: 0.06
name: Template-Plugin-Tooltip
author: Adam Kennedy <cpan@ali.as>
license: perl
build_requires: 
  Test::More: 0.47
  File::Spec: 0.80
requires: 
  Scalar::Util: 1.15
  perl: 5.005
  HTML::Tooltip::Javascript: 0.03
  Template: 2.10
abstract: Template Toolkit plugin for HTML::Tooltip::JavaScript
